In [0]:
print('Bonjour à tous')

- Contexte (principes généraux du langage, IDE, chez nous)
- Prise en main (print('Hello world') dans un notebook Jupyter)
- Les boucles (indentation, indexation depuis 0, for, if, while, return, break)
- Les fonctions
- Les types de base (string, lists, tuples, dicts, bool)
- La manipulation de listes (indexing, append, comprehension lists , map, filter, reduce, lambda expression)
- La manipulation de strings (concaténation, indexation, formattage)
- La manipulation de dictionnaires (création, ajout d’un élément, boucle, items)
- Les packages (import, from, as)
- Numpy (opérations de base)
- Optionnel : try/except, classes

# IDE

A la base, python est un langage de programmation. Il est donc possible de l'utiliser dans un IDE traditionnel comme Visual Studio Code, PyCharm... 

L'usage de python pour la data science nécessite cependant une certaine agilité car beaucoup d'études exploratoires sont plus accées sur la rapidité d'obtention des premiers résultats que sur la scalabilité ou la robustesse. Aussi, jupyter propose un environnement simple dans lequel on peut programmer, organiser et visualiser les résultats rapidement, comme les notebooks R studio. 

- Pour commencer à prendre en main l'interface, cliquez sur le menu

`Aide` -> `Visite de l'interface utilisateur`

- Pour commencer à vous familiariser avec les raccourcis clavier, cliquez sur

`Aide` -> `Raccourcis clavier`

- Pour exécuter les cellules suivantes, appuyez sur les touches `Maj+Entr`.

Contrairement à R studio, vous ne pouvez pas exécuter une seule ligne à la fois. Mais n'éhistez pas à créer des cellules d'une seule ligne si nécessaire (avec les raccourcis `B` et `A` par exemple) puis les supprimer (avec `X`) ou les merger (avec `M`)

# Opérateurs

**Les opérateurs sont identiques en R et en Python...**

... a part l'assignation `<-` qui devient `=`.

Python est un langage conçu pour être simple et compréhensible. Les opérations logiques sont donc simplement écrites en anglais : 
- `!x` en R devient `not x` en python
- `x | y` en R devient`x or y` en python
- `x & y` en R devient `x or y` en python

Stockez les valeurs 2 et 5 dans deux variables nommée respectivement a et b. 

In [2]:
a = 2
b = 5

Effectuez quelques tests sur ces variables : 
- Est-ce que a est égal à b ? 
- Est-ce que a est inférieur b ?
- Est-ce que a est inférieur ou égal à b et est-ce que b est inférieur à 6 ?

In [3]:
a == b

False

In [4]:
a < b

True

In [5]:
a <= b and b < 6

True

Page de référence : https://www.tutorialspoint.com/python/python_basic_operators.htm

# Boucles
En python, les **espaces et tabulations** en début de ligne font partie de la synthaxe. Ce sont notamment elles qui déterminent à quel niveau de boucle se trouve la ligne en question.

## Exemples de boucles

In [18]:
a = 3

**Boucle if + condition**

In [19]:
if a > 3:
    print("a est plus grand que 3")

**Else**

In [20]:
if a > 3:
    print("a est plus grand que 3")
else : 
    print("a est plus petit que 3")

a est plus petit que 3


**Elif**

In [21]:
if a > 3:
    print("a est plus grand que 3")
elif a == 3:
    print("a est égal à 3")
elif a >= 3:
    print("a est supérieur ou égal à 3")
else : 
    print("a est plus petit que 3")

a est égal à 3


**Boucle while**

In [27]:
a = 0
while a < 5:
    print(a)
    a += 1

0
1
2
3
4


**Boucle for**

In [29]:
for i in range(5):
    print(i)

0
1
2
3
4


**Break et continue**

In [46]:
for i in range(5):
    if i == 3:
        break
    print(i)

print("The end")

0
1
2
The end


In [47]:
for i in range(5):
    if i == 3:
        continue
    print(i)

print("The end")

0
1
2
4
The end


## Exercices

Afficher les nombres entiers de 1 à 5 en utilisant une boucle while

In [34]:
i = 1
while i <= 5:
    print(i)
    i += 1

1
2
3
4
5


- Ecrire un code qui calcule la somme cumulative de tous les entiers paires jusqu'à ce que cette somme soit supérieure à 50.

In [49]:
# Correction 1
somme = 0
i = 0

while somme < 50:
    if i%2 == 0:
        somme += i
        print(somme)
    
    i+= 1

0
2
6
12
20
30
42
56


In [50]:
# correction 2
somme = 0
i = 0

for i in range(0, 100, 2):
    somme += i
    print(somme)
    if somme > 50:
        break

0
2
6
12
20
30
42
56


- Ecrire un code qui affiche le résultat suivant : 

```
1
333
55555
7777777
999999999
```

In [42]:
a = 1 
while a < 10:
    for i in range(a):
        if a%2 == 1 and i == a-1:
            print(a)
        elif a%2 == 1:
            print(a, end='')
    a += 1

1
333
55555
7777777
999999999


# Fonctions

Commençons par une fonction simple :

    1. Écrivons une fonction qui nous permette de sortir à la racine carré d’un nombre. On l’appellera *sqrt()*

In [2]:
def sqrt(nombre):
    nombre = nombre ** (1/2)
    print(nombre)
    
sqrt(9)

3.0


# Types de bases

## Listes

Voici une liste [“Bonjour”, “Je”, “Christophe”, “m’appelle”]

1. Stocker cette liste dans une variable qu’on appellera christophe
2. Faites une boucle pour que la console retourne chacun des items de la liste

In [5]:
Christophe = ["Bonjour", "Je", "Christophe", "m'appelle"]
for mot in Christophe:
    print(mot)

Bonjour
Je
Christophe
m'appelle


On a un problème avec cette phrase, deux mots sont inversés. Trouvez un moyen d’inverser le dernier item avec l’avant dernier

In [6]:
prenom = Christophe.pop(2)
Christophe.append(prenom)
for mot in Christophe:
    print(mot)

Bonjour
Je
m'appelle
Christophe


Voici une liste d’âge : [12, 16, 34, 58, 9].

    1. Stockez cette liste d’âge dans une variable qu’on appellera 



```
age
```



    2. On aimerait que cette liste soit rangée par ordre croissant, comment faire ?

In [7]:
age = [12,16,34,58,9]
ordre = age.pop(4)
age.insert(0,ordre)
print(age)

[9, 12, 16, 34, 58]


### Les slices

 On a le dataset suivant : `km_parcourus = [50, 10, 100, 25, 1000, 21, 12,30]`
 
    1. Cette variable représente une liste de kilomètres parcourus tous les matins par 8 utilisateurs pour aller au travail
    2. En utilisant une boucle, calculez la moyenne total parcouru par tous les utilisateurs
    3. Est ce que cette moyenne est représentative de ce que tous les individus parcourent vraiment ? A votre avis pourquoi ?

In [12]:
km_parcourus = [50, 10, 100, 25, 1000, 21, 12,30]
individus = 0
total_individus = 0

for individu in km_parcourus:
    individus += individu
    total_individus += 1

moyenne_km = individus/total_individus
print("En moyenne, les utilisateurs ont parcourus {} km pour aller au travail".format(moyenne_km))

En moyenne, les utilisateurs ont parcourus 156.0 km pour aller au travail


    4. Changez la variable _km_parcourus_ pour avoir une moyenne plus représentative

In [14]:
km_parcourus = km_parcourus[0:3] + km_parcourus[5:]
individus = 0
total_individus = 0

for individu in km_parcourus:
    individus += individu
    total_individus += 1

moyenne_km = individus/total_individus
print("En moyenne, les utilisateurs ont parcourus {} km pour aller au travail".format(moyenne_km))

En moyenne, les utilisateurs ont parcourus 47.5 km pour aller au travail


## Les dictionnaires

# Manipulations de listes

# Manipulations de string

# Manipulation de dictionnaires

# Packages

# Numpy

In [17]:
import numpy as np

## Manipulation de vecteur

In [26]:
D = np.array([1, 8, 5, 4, 6, 2, 0, 9, 7, 3])
med = np.array([2, 5, 3])

### Verifier le type des données
Contenues dans le vecteur D

In [19]:
type(D)

numpy.ndarray

In [20]:
D.dtype

dtype('int64')

### Maintenant que ce type est connu, extraire les valeurs stockées sur les indices impairs
Toujours avec le vecteur D

In [21]:
D

array([1, 8, 5, 4, 6, 2, 0, 9, 7, 3])

In [22]:
D[1::2]

array([8, 4, 2, 9, 3])

In [23]:
D_impair = np.array([])
for i in range(len(D)):
    if i%2 == 1:
        D_impair = np.append(D_impair, D[i])

In [24]:
D_impair.astype(int)

array([8, 4, 2, 9, 3])

### Récupérer la médiane du vecteur des indices impairs

In [25]:
med_d = np.median(D_impair)

### Ajouter cette valeur à la fin du vecteur med

In [27]:
med = np.append(med, med_d)

In [28]:
med.astype(int)

array([2, 5, 3, 4])

### Identifier l'id client qui a le plus depensé
A titre d'information, le 3e éléments du vecteur depense_client correspond à la somme dépensée par l'id client en 3e position dans le vecteur id_client

In [29]:
id_client = np.array([31,  5, 38, 68, 86, 98, 72, 23, 51, 66, 36, 33, 92, 69, 29])
depense_client = np.array([297.24, 208.66, 166.67,  335.62, 140.21, 286.48,  88.94,  46.04,
        86.18, 274.38, 169.32, 173.11, 273.64, 239.18,  40.3 ])

In [30]:
index_max = np.argmax(depense_client)
index_max

3

In [31]:
id_client[index_max]

68

### Trier les vecteurs id_client et depense_client par somme dépensée décroissante

In [32]:
tri = np.argsort(depense_client)
tri_invers = tri[::-1]

In [33]:
id_client[tri_invers]

array([68, 31, 98, 66, 92, 69,  5, 33, 36, 38, 86, 72, 51, 23, 29])

In [34]:
depense_client[tri_invers]

array([335.62, 297.24, 286.48, 274.38, 273.64, 239.18, 208.66, 173.11,
       169.32, 166.67, 140.21,  88.94,  86.18,  46.04,  40.3 ])

### Générer un array de 30 entiers aléatoirement entre 1 et 12

### Générer un array de 30 flotants aléatoirements entre 0 et 50 avec deux chiffres après la virgule

In [153]:
np.round((np.random.random(30)*50), 2)

array([39.21, 30.14, 34.66,  3.73, 17.72, 25.77, 21.87, 38.38,  9.54,
       29.47, 42.02, 11.46, 13.92, 24.16,  8.75, 23.69, 11.99, 23.21,
       22.01, 26.54, 34.43, 20.67, 41.9 , 35.54,  5.77, 11.33, 36.08,
       13.24, 14.48, 20.03])

In [83]:
### Générer un array de 30 flotants aléatoirements entre 0 et 50 avec deux chiffres après la virgule

np.round((np.random.random(30)*50), 2)np.random.seed(2)
(np.random.randint(1, 13, 30))

array([ 9,  9,  7, 12,  3, 12,  9,  8,  3,  2, 12,  6, 11,  5,  5,  6,  8,
        4,  7,  5, 11, 12,  4,  8,  7, 11,  2, 11,  4,  6])

## Part 2 matrice

### Travail de modelage


In [155]:
coefficient = np.array(
    [[-1.01324867,  1.1871035 , -1.65190239, -1.58638258],
     [ 0.50434212, -0.72520265, -0.27197777, -0.8131409 ],
     [ 0.50890656, -0.46190086,  1.92388016,  2.39952348]])
famille = ['setosa', 'versicolor', 'virginica']
variable = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Dans la matrice coefficient, Chaque ligne correspond à une famille d'iris, et chaque colonne à une variable. L'objectif est de créer le tableau suivant.


Fonctions de numpy pertinentes: ravel, tile, repeat, transpose, array

In [159]:
coefficient = np.array(coefficient)
famille = np.array(famille)
variable = np.array(variable)

In [160]:
coefficient.ravel()
np.repeat(famille, 4)
np.tile(variable, 3)

array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'sepal length (cm)', 'sepal width (cm)',
       'petal length (cm)', 'petal width (cm)', 'sepal length (cm)',
       'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'],
      dtype='<U17')

In [163]:
np.array([coefficient.ravel(), 
          np.repeat(famille, 4), 
          np.tile(variable, 3)]).T

array([['-1.01324867', 'setosa', 'sepal length (cm)'],
       ['1.1871035', 'setosa', 'sepal width (cm)'],
       ['-1.65190239', 'setosa', 'petal length (cm)'],
       ['-1.58638258', 'setosa', 'petal width (cm)'],
       ['0.50434212', 'versicolor', 'sepal length (cm)'],
       ['-0.72520265', 'versicolor', 'sepal width (cm)'],
       ['-0.27197777', 'versicolor', 'petal length (cm)'],
       ['-0.8131409', 'versicolor', 'petal width (cm)'],
       ['0.50890656', 'virginica', 'sepal length (cm)'],
       ['-0.46190086', 'virginica', 'sepal width (cm)'],
       ['1.92388016', 'virginica', 'petal length (cm)'],
       ['2.39952348', 'virginica', 'petal width (cm)']], dtype='<U32')

In [ ]:
# Objectif
np.array([['-1.0132486724005245', 'sepal length (cm)', 'setosa'],
       ['1.1871035025418413', 'sepal width (cm)', 'setosa'],
       ['-1.6519023926009897', 'petal length (cm)', 'setosa'],
       ['-1.5863825821769832', 'petal width (cm)', 'setosa'],
       ['0.5043421152883055', 'sepal length (cm)', 'versicolor'],
       ['-0.7252026471041335', 'sepal width (cm)', 'versicolor'],
       ['-0.27197777085733216', 'petal length (cm)', 'versicolor'],
       ['-0.8131408997489712', 'petal width (cm)', 'versicolor'],
       ['0.5089065571122178', 'sepal length (cm)', 'virginica'],
       ['-0.4619008554377047', 'sepal width (cm)', 'virginica'],
       ['1.9238801634583182', 'petal length (cm)', 'virginica'],
       ['2.399523481925951', 'petal width (cm)', 'virginica']])

# try except