In [0]:
print('Bonjour à tous')

- Contexte (principes généraux du langage, IDE, chez nous)
- Prise en main (print('Hello world') dans un notebook Jupyter)
- Les boucles (indentation, indexation depuis 0, for, if, while, return, break)
- Les fonctions
- Les types de base (string, lists, tuples, dicts, bool)
- La manipulation de listes (indexing, append, comprehension lists , map, filter, reduce, lambda expression)
- La manipulation de strings (concaténation, indexation, formattage)
- La manipulation de dictionnaires (création, ajout d’un élément, boucle, items)
- Les packages (import, from, as)
- Numpy (opérations de base)
- Optionnel : try/except, classes

# IDE

A la base, python est un langage de programmation. Il est donc possible de l'utiliser dans un IDE traditionnel comme Visual Studio Code, PyCharm... 

L'usage de python pour la data science nécessite cependant une certaine agilité car beaucoup d'études exploratoires sont plus accées sur la rapidité d'obtention des premiers résultats que sur la scalabilité ou la robustesse. Aussi, jupyter propose un environnement simple dans lequel on peut programmer, organiser et visualiser les résultats rapidement, comme les notebooks R studio. 

- Pour commencer à prendre en main l'interface, cliquez sur le menu

`Aide` -> `Visite de l'interface utilisateur`

- Pour commencer à vous familiariser avec les raccourcis clavier, cliquez sur

`Aide` -> `Raccourcis clavier`

- Pour exécuter les cellules suivantes, appuyez sur les touches `Maj+Entr`.

Contrairement à R studio, vous ne pouvez pas exécuter une seule ligne à la fois. Mais n'éhistez pas à créer des cellules d'une seule ligne si nécessaire (avec les raccourcis `B` et `A` par exemple) puis les supprimer (avec `X`) ou les merger (avec `M`)

# Opérateurs

**Les opérateurs sont identiques en R et en Python...**

... a part l'assignation `<-` qui devient `=`.

Python est un langage conçu pour être simple et compréhensible. Les opérations logiques sont donc simplement écrites en anglais : 
- `!x` en R devient `not x` en python
- `x | y` en R devient`x or y` en python
- `x & y` en R devient `x or y` en python

Stockez les valeurs 2 et 5 dans deux variables nommée respectivement a et b. 

In [2]:
a = 2
b = 5

Effectuez quelques tests sur ces variables : 
- Est-ce que a est égal à b ? 
- Est-ce que a est inférieur b ?
- Est-ce que a est inférieur ou égal à b et est-ce que b est inférieur à 6 ?

In [3]:
a == b

False

In [4]:
a < b

True

In [5]:
a <= b and b < 6

True

Page de référence : https://www.tutorialspoint.com/python/python_basic_operators.htm

# Boucles
En python, les **espaces et tabulations** en début de ligne font partie de la synthaxe. Ce sont notamment elles qui déterminent à quel niveau de boucle se trouve la ligne en question.

## Exemples de boucles

In [18]:
a = 3

**Boucle if + condition**

In [19]:
if a > 3:
    print("a est plus grand que 3")

**Else**

In [20]:
if a > 3:
    print("a est plus grand que 3")
else : 
    print("a est plus petit que 3")

a est plus petit que 3


**Elif**

In [21]:
if a > 3:
    print("a est plus grand que 3")
elif a == 3:
    print("a est égal à 3")
elif a >= 3:
    print("a est supérieur ou égal à 3")
else : 
    print("a est plus petit que 3")

a est égal à 3


**Boucle while**

In [27]:
a = 0
while a < 5:
    print(a)
    a += 1

0
1
2
3
4


**Boucle for**

In [29]:
for i in range(5):
    print(i)

0
1
2
3
4


**Break et continue**

In [46]:
for i in range(5):
    if i == 3:
        break
    print(i)

print("The end")

0
1
2
The end


In [47]:
for i in range(5):
    if i == 3:
        continue
    print(i)

print("The end")

0
1
2
4
The end


## Exercices

- Afficher les entiers n entre 200 et 600 tels que, n est multiple de 7 et n au cube est multiple de 50

In [52]:
for n in range(200, 601):
    if (n % 7 == 0) and (n**3 % 50 == 0):
        print(n)

210
280
350
420
490
560


- Ecrire un code qui calcule la somme cumulative de tous les entiers paires jusqu'à ce que cette somme soit supérieure à 50.

In [49]:
# Correction 1
somme = 0
i = 0

while somme < 50:
    if i%2 == 0:
        somme += i
        print(somme)
    
    i+= 1

0
2
6
12
20
30
42
56


In [50]:
# correction 2
somme = 0
i = 0

for i in range(0, 100, 2):
    somme += i
    print(somme)
    if somme > 50:
        break

0
2
6
12
20
30
42
56


- Ecrire un code qui affiche le résultat suivant : 

```
1
333
55555
7777777
999999999
```

In [42]:
a = 1 
while a < 10:
    for i in range(a):
        if a%2 == 1 and i == a-1:
            print(a)
        elif a%2 == 1:
            print(a, end='')
    a += 1

1
333
55555
7777777
999999999


# Fonctions

## Exemples de fonctions simples

Écrivons une fonction qui permet de calculer à la racine carré d’un nombre. On l’appellera `sqrt()`

In [53]:
def sqrt(nombre):
    nombre = nombre ** (1/2)
    return nombre
    
sqrt(9)

3.0

Les fonctions peuvent utiliser des arguments optionnels

In [58]:
def puissance(nombre, exposant=2):
    nombre = nombre ** (exposant)
    return nombre

print(puissance(3))
print(puissance(9, exposant = 1/2))
print(puissance(3, 3))

9
3.0
27


## Exercice : fonctions

Créer une fonction PRIXTTC qui prend en entrée un prix HT et le type de produit (luxe ou normal par défaut) et qui donne en sortie le prix TTC, le prix HT et la TVA. Si le produit est un produit de luxe TVA à 33% sinon TVA à 20%

In [60]:
def calcul_prix_ttc(prix_ht, type_tva='normal'):
    """
    Retourne le prix TTC, le prix HT et la TVA à partir du type de TVA et du prix HT.
    """
    if type_tva == 'luxe':
        TVA = 0.33
    else : TVA = 0.2
    
    prix_ttc = prix_ht + prix_ht * TVA
    
    return (prix_ttc, prix_ht, prix_ht * TVA)

In [61]:
calcul_prix_ttc(20, 'luxe')

(26.6, 20, 6.6000000000000005)

## Les itérateurs / générateurs

Un itérable est un objet séquentiel que l'on peut parcourir élément par élément à l'aide d'une boucle for :

**for** toto in **itérable**:
> Code

Exemples d'itérables : 
```
A = [1, 2, 3, 4, 5]
B = range(5)
```

A et B contiennent les mêmes données. Mais la grosse différence, c'est que dans la liste A, tous les éléments sont déjà calculés et stockés en mémoire. Tandis que pour l'objet B, le calcul est effectué à la volée pour chaque itération.

**C'est le principe du générateur** : une fonction qui utilise le mot-clef `yield` au lieu de `return` et qui n'est exécuté que lorsqu'elle est itérée dans une boucle `for`.

In [ ]:
def mon_generateur():
    i = 40
    while i <= 56:
        i += 2
        yield i

## Exercice : les itérateurs / générateurs

Créer un générateur infini pour la suite de Fibonacci :
```
Fib[0] = 0
Fib[1] = 1
Fib[n+2] = Fib[n] + Fib[n+1]
```

In [ ]:
def fibonacci():
    f1 = 0
    yield f1
    f2 = 1
    yield f2
    while True:
        f3 = f1 + f2
        yield f3
        f1 = f2
        f2 = f3

# Types de bases

## Listes

Les listes python sont des itérables très utilisés. Ils permettent de stocker une série d'éléments qui peuvent être de type différent.

Prenons un exemple de liste de chaînes de charactères :
```
[“Bonjour”, “Je”, “Christophe”, “m’appelle”]
```

- Stockez cette liste dans une variable qu’on appellera `Christophe`
- Faites une boucle pour afficher chacun des items de la liste

In [75]:
Christophe = ["Bonjour", "Je", "Christophe", "m'appelle"]
for mot in Christophe:
    print(mot)

Bonjour
Je
Christophe
m'appelle


## Les dictionnaires

```
D = {
    clé1 : valeur1,
    clé2 : valeur2,
}
```

Les dictionnaires sont des objets pouvant en contenir d'autres, à l'instar des listes. Cependant, au lieu d'héberger des informations dans un ordre précis, **ils associent chaque objet contenu à une clé** (la plupart du temps, une chaîne de caractères). Par exemple, un dictionnaire peut contenir un carnet d'adresses et on accède à chaque contact en précisant son nom.

- Créer un dictionnaire avec les couples clés-valeurs suivants:  
('Batman','Robin')  
('Harley Quinn','Poison Ivy')  
('Iron man','War machine')  
('Phenix','Cyclope')

In [112]:
dico_duo = {
    'Batman':'Robin',
    'Harley Quinn':'Poison Ivy',
    'Iron man':'War machine',
    'Phenix':'Cyclope'
}
dico_duo

{'Batman': 'Robin',
 'Harley Quinn': 'Poison Ivy',
 'Iron man': 'War machine',
 'Phenix': 'Cyclope'}

- Acceder au partenaire de `'Phenix'` en utilisant les `[]`

In [114]:
dico_duo['Phenix']

'Cyclope'

- Remplacer la valeur associée à la clé `'Phenix'` par `'Jean Grey'`

In [115]:
dico_duo['Phenix'] = 'Jean Grey'
dico_duo

{'Batman': 'Robin',
 'Harley Quinn': 'Poison Ivy',
 'Iron man': 'War machine',
 'Phenix': 'Jean Grey'}

- Ajouter le duo `'Ant man'` et `'the Wasp'` au dictionnaire

In [116]:
dico_duo['Ant man'] = 'The Wasp'
dico_duo

{'Batman': 'Robin',
 'Harley Quinn': 'Poison Ivy',
 'Iron man': 'War machine',
 'Phenix': 'Jean Grey',
 'Ant man': 'The Wasp'}

## Les tuples

Les tuples sont des listes immutables, c'est-à-dire que leurs valeurs ne peuvent pas être modifiées. Leur définition se fait avec `()` et leur manipulation est similaire à celle des listes.

Exemple :
```
foo = (1, 2, 3)
```

# Manipulations de listes

## Les basiques

**`list[i]`**
> Renvoie le ième élément de la liste. Attention, l'indexation des listes commence à 0 en python !

**`len(list)`**
> Renvoie le nombre d'éléments de la liste

**`list.append(x)`**
> Ajoute un élément à la fin de la liste ; équivalent à `a[len(a):] = [x]`.

**`list1 + list2`**
> Concaténation de `list1` et `list2`

**`list[ début : fin ]`**
> Slicing classique

<img src="ressource/slice_1.png" style="height:100px"/>

**`list[-n]`**
> Slicing négatif : nième élément en partant de la fin.

<img src="ressource/slice_2.png" style="height:180px"/>

**`list[ début : fin : s]`**
> Slicing par pas : Tous les s éléments.

<img src="ressource/slice_3.png" style="height:110px"/>

Plus d'aide : 
https://docs.python.org/fr/3/tutorial/datastructures.html
https://zestedesavoir.com/tutoriels/582/les-slices-en-python/

### Exercices

In [78]:
Christophe = ["Bonjour", "Je", "Christophe", "m'appelle"]

On a un problème avec cette phrase, deux mots sont inversés. Trouvez un moyen d’inverser le dernier item avec l’avant dernier. Un peu d'aide sur les manipulations de liste :

In [77]:
prenom = Christophe.pop(2)
Christophe.append(prenom)
for mot in Christophe:
    print(mot)

Bonjour
Je
Christophe
m'appelle


Voici une liste d’âge : [12, 16, 34, 58, 9].

    1. Stockez cette liste d’âge dans une variable qu’on appellera 



```
age
```



    2. On aimerait que cette liste soit rangée par ordre croissant, comment faire ?

In [65]:
age = [12,16,34,58,9]
ordre = age.pop(4)
age.insert(0,ordre)
print(age)

[9, 12, 16, 34, 58]


In [69]:
age = [12,16,34,58,9]
age.sort()
print(age)

[9, 12, 16, 34, 58]


### Remarque sur copy()

Attardons nous maintenant sur le concept de référence. En effet, une liste python ne contient pas des éléments mais des références (adresses mémoires) vers ces éléments. C'est ce qui rend leur usage si flexible : vous pouvez avoir une liste qui contient des entiers, des strings, et même des instances de classe. 

Cette organisation cause souvent, chez le pythoniste débutant, un trouble existentiel. En effet :

In [129]:
# Ma 1ère liste contient 1, 2, 3, 4
list1 = [1, 2, 3, 4]

In [130]:
# Je définis ma 2ème liste comme égale à la première
list2 = list1

In [131]:
# Je modifie ma première liste
list1[0] = 10

In [138]:
print(list2)
print('Fichtre, la liste 2 a été modifiée aussi...')

[10, 2, 3, -10]
Fichtre, la liste 2 a été modifiée aussi...


In [139]:
# Et maintenant si je modifie la liste 2
list2[-1] = -10
print(list1)
print('Diantre, la liste 1 a été modifiée aussi...')

[10, 2, 3, -10]
Diantre, la liste 1 a été modifiée aussi...


Lorsque vous executez `list2 = list1`, vous stockez dans la variable `list2`les références vers les objets de `list1`. De fait, lorsque vous modifiez les objets eux-mêmes, les références de `list1`et de `list2` pointent toutes les deux vers les nouveaux objets. 

**Pour pallier à ce problème, on peut utiliser la fonction `copy()`**
https://docs.python.org/3/library/copy.html

In [141]:
list1 = [1, 2, 3, 4]
list2 = list1.copy()
list1[0] = 10
list2[-1] = -10
print('list1', list1)
print('list2', list2)

list1 [10, 2, 3, 4]
list2 [1, 2, 3, -10]


## Compréhension de liste

### Synthaxe

**`list2 = [n*2 for n in list1]`**

> `list2` contient chaque élément de `list1` multiplié par 2.

La compréhension de liste est une expression qui permet de construire une liste à partir de tout autre type itérable (liste, tuple, chaîne de caractères…) en une ligne. Le résultat obtenu est toujours une liste.

### Exercice

- Calculez les carrés des entiers de 1 à 10

In [105]:
[ n**2 for n in range(1,11) ]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

- Maintenant calculez leur somme en utilisant la fonction `sum``

In [106]:
sum( [ n**2 for n in range(1,11) ] )

385

### Condition

Les compréhensions de liste peuvent aussi impliquer une condition **`if`**

In [101]:
[entier for entier in range(20) if entier%2==0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

### Exercice

- Décrire en compréhension la liste des nombres inférieurs à 20 qui sont multiples, ou bien de 5, ou bien de 7.

In [107]:
[n for n in range(20) if n%5==0 or n%7==0]

[0, 5, 7, 10, 14, 15]

- Même exercice pour les nombres multiples de 5 ou de 7 mais pas de 15.

In [108]:
[n for n in range(20) if (n%5==0 or n%7==0) and n%15!=0]

[5, 7, 10, 14]

# Manipulations de tuples

- Créer un tuple de 1 à 5

In [1]:
t = (1,2,3,4,5)

 - Accéder au chiffre 2 

In [2]:
t[1]

2

- Récupérer les valeurs allant de 1 à 3

In [3]:
t[0:3]

(1, 2, 3)

- Manipulation de tuple

In [117]:
t1 = (1, 2, 3)
t2 = (4, 5, 6)
t3 = (2, 4, 6)

- Concatener les tuples t1 avec t3 et appeler le t4

In [5]:
t4 = t1+t3

- Créer un tuple de tuple t24 contenant t2 et t4

In [6]:
t24 = (t2, t4)

- Afficher la 4e valeur du 2e tuple de t24

In [7]:
t24[1][3]

2

# Manipulations de string

En python, les chaines de charactères (strings) sont manipulables comme des listes contenant des charactères. 

# Manipulation de dictionnaires

**`for k in dict:`**

> Lorsqu'on itère sur un dictionnaire, on incrémente la clé. Pour obtenir la valeur, il suffit de faire `dict[k]` dans la boucle.

**`dict.items()`**

> La fonction `items()` renvoie les couples (clé, valeur) du dictionnaire. Il est possible d'itérer dessus de la manière suivante : `for k,v in dict.items()`

**`dict.values()`**

> La fonction `values()` renvoie les valeurs du dictionnaire.

In [126]:
d = {'nom': 'Dupuis', 'prenom': 'Jacques', 'age': 30}

# Packages

# Numpy

In [17]:
import numpy as np

## Manipulation de vecteur

In [26]:
D = np.array([1, 8, 5, 4, 6, 2, 0, 9, 7, 3])
med = np.array([2, 5, 3])

### Verifier le type des données
Contenues dans le vecteur D

In [19]:
type(D)

numpy.ndarray

In [20]:
D.dtype

dtype('int64')

### Maintenant que ce type est connu, extraire les valeurs stockées sur les indices impairs
Toujours avec le vecteur D

In [21]:
D

array([1, 8, 5, 4, 6, 2, 0, 9, 7, 3])

In [22]:
D[1::2]

array([8, 4, 2, 9, 3])

In [23]:
D_impair = np.array([])
for i in range(len(D)):
    if i%2 == 1:
        D_impair = np.append(D_impair, D[i])

In [24]:
D_impair.astype(int)

array([8, 4, 2, 9, 3])

### Récupérer la médiane du vecteur des indices impairs

In [25]:
med_d = np.median(D_impair)

### Ajouter cette valeur à la fin du vecteur med

In [27]:
med = np.append(med, med_d)

In [28]:
med.astype(int)

array([2, 5, 3, 4])

### Identifier l'id client qui a le plus depensé
A titre d'information, le 3e éléments du vecteur depense_client correspond à la somme dépensée par l'id client en 3e position dans le vecteur id_client

In [29]:
id_client = np.array([31,  5, 38, 68, 86, 98, 72, 23, 51, 66, 36, 33, 92, 69, 29])
depense_client = np.array([297.24, 208.66, 166.67,  335.62, 140.21, 286.48,  88.94,  46.04,
        86.18, 274.38, 169.32, 173.11, 273.64, 239.18,  40.3 ])

In [30]:
index_max = np.argmax(depense_client)
index_max

3

In [31]:
id_client[index_max]

68

### Trier les vecteurs id_client et depense_client par somme dépensée décroissante

In [32]:
tri = np.argsort(depense_client)
tri_invers = tri[::-1]

In [33]:
id_client[tri_invers]

array([68, 31, 98, 66, 92, 69,  5, 33, 36, 38, 86, 72, 51, 23, 29])

In [34]:
depense_client[tri_invers]

array([335.62, 297.24, 286.48, 274.38, 273.64, 239.18, 208.66, 173.11,
       169.32, 166.67, 140.21,  88.94,  86.18,  46.04,  40.3 ])

### Générer un array de 30 entiers aléatoirement entre 1 et 12

### Générer un array de 30 flotants aléatoirements entre 0 et 50 avec deux chiffres après la virgule

In [153]:
np.round((np.random.random(30)*50), 2)

array([39.21, 30.14, 34.66,  3.73, 17.72, 25.77, 21.87, 38.38,  9.54,
       29.47, 42.02, 11.46, 13.92, 24.16,  8.75, 23.69, 11.99, 23.21,
       22.01, 26.54, 34.43, 20.67, 41.9 , 35.54,  5.77, 11.33, 36.08,
       13.24, 14.48, 20.03])

In [83]:
### Générer un array de 30 flotants aléatoirements entre 0 et 50 avec deux chiffres après la virgule

np.round((np.random.random(30)*50), 2)np.random.seed(2)
(np.random.randint(1, 13, 30))

array([ 9,  9,  7, 12,  3, 12,  9,  8,  3,  2, 12,  6, 11,  5,  5,  6,  8,
        4,  7,  5, 11, 12,  4,  8,  7, 11,  2, 11,  4,  6])

## Part 2 matrice

### Travail de modelage


In [155]:
coefficient = np.array(
    [[-1.01324867,  1.1871035 , -1.65190239, -1.58638258],
     [ 0.50434212, -0.72520265, -0.27197777, -0.8131409 ],
     [ 0.50890656, -0.46190086,  1.92388016,  2.39952348]])
famille = ['setosa', 'versicolor', 'virginica']
variable = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Dans la matrice coefficient, Chaque ligne correspond à une famille d'iris, et chaque colonne à une variable. L'objectif est de créer le tableau suivant.


Fonctions de numpy pertinentes: ravel, tile, repeat, transpose, array

In [159]:
coefficient = np.array(coefficient)
famille = np.array(famille)
variable = np.array(variable)

In [160]:
coefficient.ravel()
np.repeat(famille, 4)
np.tile(variable, 3)

array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'sepal length (cm)', 'sepal width (cm)',
       'petal length (cm)', 'petal width (cm)', 'sepal length (cm)',
       'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'],
      dtype='<U17')

In [163]:
np.array([coefficient.ravel(), 
          np.repeat(famille, 4), 
          np.tile(variable, 3)]).T

array([['-1.01324867', 'setosa', 'sepal length (cm)'],
       ['1.1871035', 'setosa', 'sepal width (cm)'],
       ['-1.65190239', 'setosa', 'petal length (cm)'],
       ['-1.58638258', 'setosa', 'petal width (cm)'],
       ['0.50434212', 'versicolor', 'sepal length (cm)'],
       ['-0.72520265', 'versicolor', 'sepal width (cm)'],
       ['-0.27197777', 'versicolor', 'petal length (cm)'],
       ['-0.8131409', 'versicolor', 'petal width (cm)'],
       ['0.50890656', 'virginica', 'sepal length (cm)'],
       ['-0.46190086', 'virginica', 'sepal width (cm)'],
       ['1.92388016', 'virginica', 'petal length (cm)'],
       ['2.39952348', 'virginica', 'petal width (cm)']], dtype='<U32')

In [ ]:
# Objectif
np.array([['-1.0132486724005245', 'sepal length (cm)', 'setosa'],
       ['1.1871035025418413', 'sepal width (cm)', 'setosa'],
       ['-1.6519023926009897', 'petal length (cm)', 'setosa'],
       ['-1.5863825821769832', 'petal width (cm)', 'setosa'],
       ['0.5043421152883055', 'sepal length (cm)', 'versicolor'],
       ['-0.7252026471041335', 'sepal width (cm)', 'versicolor'],
       ['-0.27197777085733216', 'petal length (cm)', 'versicolor'],
       ['-0.8131408997489712', 'petal width (cm)', 'versicolor'],
       ['0.5089065571122178', 'sepal length (cm)', 'virginica'],
       ['-0.4619008554377047', 'sepal width (cm)', 'virginica'],
       ['1.9238801634583182', 'petal length (cm)', 'virginica'],
       ['2.399523481925951', 'petal width (cm)', 'virginica']])

# try except