In [1]:
print('Bonjour à tous')

Bonjour à tous


- Contexte (principes généraux du langage, IDE, chez nous)
- Prise en main (print('Hello world') dans un notebook Jupyter)
- Les boucles (indentation, indexation depuis 0, for, if, while, return, break)
- Les fonctions
- Les types de base (string, lists, tuples, dicts, bool)
- La manipulation de listes (indexing, append, comprehension lists , map, filter, reduce, lambda expression)
- La manipulation de strings (concaténation, indexation, formattage)
- La manipulation de dictionnaires (création, ajout d’un élément, boucle, items)
- Les packages (import, from, as)
- Numpy (opérations de base)
- Optionnel : try/except, classes

# Contexte


## Python

Python est un langage de programmation développé depuis les années 1990, qui connaît une popularité croissante dans le domaine de la data science ces dernières années.

Tandis que R est un langage spécifique pour les statistiques (*Domain Specific Language*), Python est un langage généraliste utilisé autant en data science que pour du développement web ou d'applications. En pratique, cela signifie que certains concepts utiles en data science ne sont pas présents directement dans le langage (data frames, valeurs manquantes, calcul matriciel, ...), mais cela est compensé par différents packages :
- **numpy** pour le calcul matriciel
- **pandas** pour les data frames
- **scikit-learn** pour le machine learning
- etc.

Grâce à ces packages, Python est notamment particulièrement utilisé pour le machine learning (notamment le deep learning).

Le caractère généraliste de Python permet de faire facilement des ponts en domaines (data science, data engineering, développement web, etc.) et de profiter d'outils communs puissants.

Sur le plan technique, Python est un langage interprété (comme R) et non compilé (C++, Java). Cela fait perdre en performances, mais permet de développer de manière plus interactive. De même il utilise un typage dynamique (c'est-à-dire que ce n'est pas le développeur qui spécifie le type des variables) pour un développement plus flexible.

Pendant de nombreuses années, les développeurs étaient partagés entre les versions 2 et 3. En effet, Python 3 a introduit des modifications importantes parfois incompatibles avec Python 2 (par exemple, en Python 3, on utilise `print('Bonjour')` alors que Python 2 utilisait `print 'Bonjour'`. De nombreux développeurs ont donc été réticents à franchir le pas, malgré les améliorations apportées par les dernières versions. Cette situation a duré plusieurs années, mais depuis début 2020 Python 2 n'a officiellement plus de support. Il n'y a donc plus d'excuse pour utiliser cette version obsolète.

## IDE

À la base, python est un langage de programmation. Il est donc possible de l'utiliser dans un IDE traditionnel comme Visual Studio Code, PyCharm... 

L'usage de Python pour la data science nécessite cependant une certaine agilité car beaucoup d'études exploratoires sont plus axées sur la rapidité d'obtention des premiers résultats que sur la scalabilité ou la robustesse. Aussi, Jupyter propose un environnement simple dans lequel on peut programmer, organiser et visualiser les résultats rapidement, comme les notebooks RStudio. C'est l'outil le plus couramment utilisé en data science, et notamment c'est celui qui est mis à disposition sur le serveur de développement de l'équipe

- Pour commencer à prendre en main l'interface, cliquez sur le menu

`Aide` -> `Visite de l'interface utilisateur`

- Pour commencer à vous familiariser avec les raccourcis clavier, cliquez sur

`Aide` -> `Raccourcis clavier`

- Un notebook est constitué de cellules pouvant être de différents types, notamment `markdown` et `code`

- Pour exécuter une cellule suivante, appuyez sur les touches `Maj+Entr`.

Contrairement à RStudio, vous ne pouvez pas exécuter une seule ligne à la fois. Mais n'hésitez pas à créer des cellules d'une seule ligne si nécessaire (avec les raccourcis `B` et `A` par exemple) puis les supprimer (avec `X`) ou les merger (avec `M`)

# Opérateurs

**Les opérateurs sont identiques en R et en Python...**

... a part l'assignation `<-` qui devient `=`.

Python est un langage conçu pour être simple et compréhensible. Les opérations logiques sont donc simplement écrites en anglais : 
- `!x` en R devient `not x` en python
- `x | y` en R devient`x or y` en python
- `x & y` en R devient `x or y` en python

Stockez les valeurs 2 et 5 dans deux variables nommée respectivement a et b. 

In [2]:
a = 2
b = 5

Effectuez quelques tests sur ces variables : 
- Est-ce que a est égal à b ? 
- Est-ce que a est inférieur b ?
- Est-ce que a est inférieur ou égal à b et est-ce que b est inférieur à 6 ?

In [3]:
a == b

False

In [4]:
a < b

True

In [5]:
a <= b and b < 6

True

# Boucles

Dans la plupart des langages, les blocs sont délimités par des accolades, et l'utilisateur peut utiliser des espaces et des tabulations pour indenter son code à sa guise. Cela permet de faire un code fonctionnel et/ou lisible. Python a un parti pris original : il considère qu'on bon code doit être lisible et qu'on peut donc donner un sens à l'indentation. Les **espaces et tabulations** en début de ligne font donc partie de la syntaxe et permettent de déterminer le niveau d'un bloc, et un code mal indenté ne fonctionnera pas.

## Exemples de boucles

In [6]:
a = 3

**Boucle if + condition**

In [7]:
if a > 3:
    print("a est plus grand que 3")
    print('Ce texte est dans le if')
    
print('Ce texte est hors du if')

Ce texte est hors du if


**Else**

In [8]:
if a > 3:
    print("a est plus grand que 3")
else : 
    print("a est plus petit que 3")

a est plus petit que 3


**Elif**

In [9]:
if a > 3:
    print("a est plus grand que 3")
elif a == 3:
    print("a est égal à 3")
elif a >= 3:
    print("a est supérieur ou égal à 3")
else : 
    print("a est plus petit que 3")

a est égal à 3


**Boucle while**

In [10]:
a = 0
while a < 5:
    print(a)
    a += 1

0
1
2
3
4


**Boucle for**

In [11]:
for i in range(5):
    print(i)

0
1
2
3
4


**Break et continue**

In [12]:
for i in range(5):
    if i == 3:
        break
    print(i)

print("The end")

0
1
2
The end


In [13]:
for i in range(5):
    if i == 3:
        continue
    print(i)

print("The end")

0
1
2
4
The end


## Exercices

- Afficher les entiers n entre 200 et 600 tels que, n est multiple de 7 et n au cube est multiple de 50

In [14]:
for n in range(200, 601):
    if (n % 7 == 0) and (n**3 % 50 == 0):
        print(n)

210
280
350
420
490
560


- Ecrire un code qui calcule la somme cumulative de tous les entiers paires jusqu'à ce que cette somme soit supérieure à 50.

In [15]:
# Correction 1
somme = 0
i = 0

while somme < 50:
    if i%2 == 0:
        somme += i
        print(somme)
    
    i+= 1

0
2
6
12
20
30
42
56


In [16]:
# correction 2
somme = 0
i = 0

for i in range(0, 100, 2):
    somme += i
    print(somme)
    if somme > 50:
        break

0
2
6
12
20
30
42
56


- Ecrire un code qui affiche le résultat suivant : 

```
1
333
55555
7777777
999999999
```

In [17]:
a = 1 
while a < 10:
    for i in range(a):
        if a%2 == 1 and i == a-1:
            print(a)
        elif a%2 == 1:
            print(a, end='')
    a += 1

1
333
55555
7777777
999999999


# Fonctions

## Exemples de fonctions simples

Écrivons une fonction qui permet de calculer à la racine carré d’un nombre. On l’appellera `sqrt()`

In [18]:
def sqrt(nombre):
    nombre = nombre ** (1/2)
    return nombre
    
sqrt(9)

3.0

Les fonctions peuvent utiliser des arguments optionnels

In [19]:
def puissance(nombre, exposant=2):
    nombre = nombre ** (exposant)
    return nombre

print(puissance(3))
print(puissance(9, exposant = 1/2))
print(puissance(3, 3))

9
3.0
27


Une fonction peut retourner plusieurs valeurs

In [20]:
def puissance(nombre):
    return nombre, nombre**2, nombre**3

x, y, z = puissance(3)

print(x)
print(y)
print(z)

3
9
27


## Exercice : fonctions

Créer une fonction PRIXTTC qui prend en entrée un prix HT et le type de produit (luxe ou normal par défaut) et qui donne en sortie le prix TTC, le prix HT et la TVA. Si le produit est un produit de luxe TVA à 33% sinon TVA à 20%

In [21]:
def calcul_prix_ttc(prix_ht, type_tva='normal'):
    """
    Retourne le prix TTC, le prix HT et la TVA à partir du type de TVA et du prix HT.
    """
    if type_tva == 'luxe':
        TVA = 0.33
    else : TVA = 0.2
    
    prix_ttc = prix_ht + prix_ht * TVA
    
    return (prix_ttc, prix_ht, prix_ht * TVA)

In [22]:
calcul_prix_ttc(20, 'luxe')

(26.6, 20, 6.6000000000000005)

# Les types de variables

Comme dans tous les langages de programmation, il existe différents types de variables en python : `int`, `float`, `str`...

Python est un langage typé dynamiquement. Cela signifie que dans 90% des cas, vous n'avez pas à vous soucier du type de données que vous manipulez, du moment que vous savez ce que vous faites. Pour les 10 % restants, voici quelques astuces :

- Utilisez la fonction **`type`** pour connaître le type d'une variable.
- Utilisez la fonction **`isinstance`** pour vérifier le type d'une variable
- Utilisez les fonctions **`float`**, **`int`**, **`str`** pour convertir vos variables

In [23]:
type(0)

int

In [24]:
type('0')

str

In [25]:
str(0) == '0'

True

In [26]:
isinstance(str(0), int)

False

**Exercices**

- Affichez les types des variables suivante

In [27]:
entier = 3
reel = 1.54
mot = 'mot'

- vérifiez que *`reel`* est bien un float

In [28]:
isinstance(reel, float)

True

- Convertissez *`entier`* en `string`

In [29]:
str(entier)

'3'

# Itérables de bases

Un itérable est un objet séquentiel que l'on peut parcourir élément par élément à l'aide d'une boucle for :

<pre><code>
<b>for</b> <i>toto</i> in <b>itérable</b>:
    ... <i>toto</i> ...
</pre>

Les listes, les tuples, les ensembles, les strings et les dictionnaires sont des itérables.

## Listes

In [30]:
### Principe

Les listes python permettent de stocker une série d'éléments qui peuvent être de type différent. Prenons un exemple de liste de chaînes de charactères :
```
[“Bonjour”, “Je”, “Christophe”, “m’appelle”]
```

**Exercices**

- Stockez cette liste dans une variable qu’on appellera `Christophe`
- Affichez chacun des items de la liste à l'aide d'une boucle `for`

In [31]:
Christophe = ["Bonjour", "Je", "Christophe", "m'appelle"]
for mot in Christophe:
    print(mot)

Bonjour
Je
Christophe
m'appelle


### Manipulations de listes

## Les basiques

**`maliste[i]`**
> Renvoie le ième élément de la liste. **Attention, l'indexation des listes commence à 0 en Python !**

**`maliste[-n]`**
> Slicing négatif : nième élément en partant de la fin.

<img src="ressource/slice_2.png" style="height:180px"/>

**`len(maliste)`**
> Renvoie le nombre d'éléments de la liste

**`maliste[ début : fin ]`**
> Slicing classique

<img src="ressource/slice_1.png" style="height:100px"/>

> On peut omettre un élément, il prend alors comme valeur par défaut :
- **début** : 0
- **fin** : len(maliste)

Ainsi `maliste[2:]` prend toute la liste sauf les deux premiers éléments, tandis que `maliste[:-1]` enlève le dernier élément.

**`maliste[ début : fin : s]`**
> Slicing par pas : Tous les s éléments.

<img src="ressource/slice_3.png" style="height:110px"/>

**`maliste.append(x)`**
> Ajoute un élément à la fin de la liste ; équivalent à `a[len(a):] = [x]`.

**`maliste.insert(x, i)`**
> Insère `x` à l'indice `i` et décale les éléments suivants

**`maliste.pop(i)`**
> Enlève l'élélement à l'indice `i` et avance les éléments suivants 

**`maliste1 + maliste2`**
> Concaténation de `maliste1` et `maliste2`

> Cela signifie que `[1, 2, 3] + [4, 5, 6]` ne fait pas la somme des éléments mais donne `[1, 2, 3, 4, 5, 6]`. Python ne fait pas de calcul matriciel avec les listes !

**`n * maliste`**
> Répète n fois `maliste`. Par exemple : `2 * [0,1] = [0, 1, 0, 1]`

**`element in maliste`**
> Le mot-clé **`in`** permet de tester si une valeur se trouve dans une liste (ou de manière générale, un itérable).

Plus d'aide : 
https://docs.python.org/fr/3/tutorial/datastructures.html
https://zestedesavoir.com/tutoriels/582/les-slices-en-python/

### Exercices

- Voici une liste contenant toutes les lettres de l'alphabet

In [120]:
alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

Sélectionner les 5 premières lettres

In [125]:
alphabet[:5]

['a', 'b', 'c', 'd', 'e']

Sélectionner les 3 dernières lettres

In [124]:
alphabet[-3:]

['x', 'y', 'z']

Parmi les 5 premières lettres, sélectionner une sur deux

In [126]:
alphabet[:5:2]

['a', 'c', 'e']

Réciter l'alphabet à l'envers

In [127]:
alphabet[::-1]

['z',
 'y',
 'x',
 'w',
 'v',
 'u',
 't',
 's',
 'r',
 'q',
 'p',
 'o',
 'n',
 'm',
 'l',
 'k',
 'j',
 'i',
 'h',
 'g',
 'f',
 'e',
 'd',
 'c',
 'b',
 'a']

La lettre `é` est-elle dans la liste ?

In [133]:
"é" in alphabet

False

In [32]:
Christophe = ["Bonjour", "Je", "Christophe", "m'appelle"]

On a un problème avec cette phrase, deux mots sont inversés. Trouvez un moyen d’inverser le dernier item avec l’avant dernier, en utilisant `pop`.

In [33]:
prenom = Christophe.pop(2)
Christophe.append(prenom)
for mot in Christophe:
    print(mot)

Bonjour
Je
m'appelle
Christophe


### Remarque sur copy()

Attardons nous maintenant sur le concept de référence. En effet, une liste python ne contient pas des éléments mais des références (adresses mémoires) vers ces éléments. C'est ce qui rend leur usage si flexible : vous pouvez avoir une liste qui contient des entiers, des strings, et même des instances de classe. 

Cette organisation cause souvent, chez le pythoniste débutant, un trouble existentiel. En effet :

In [37]:
# Ma 1ère liste contient 1, 2, 3, 4
list1 = [1, 2, 3, 4]

In [38]:
# Je définis ma 2ème liste comme égale à la première
list2 = list1

In [39]:
# Je modifie ma première liste
list1[0] = 10

In [40]:
print(list2)
print('Fichtre, la liste 2 a été modifiée aussi...')

[10, 2, 3, 4]
Fichtre, la liste 2 a été modifiée aussi...


In [41]:
# Et maintenant si je modifie la liste 2
list2[-1] = -10
print(list1)
print('Diantre, la liste 1 a été modifiée aussi...')

[10, 2, 3, -10]
Diantre, la liste 1 a été modifiée aussi...


Lorsque vous executez `list2 = list1`, vous stockez dans la variable `list2`les références vers les objets de `list1`. De fait, lorsque vous modifiez les objets eux-mêmes, les références de `list1`et de `list2` pointent toutes les deux vers les nouveaux objets. 

**Pour pallier ce problème, on peut utiliser la fonction `copy()`**
https://docs.python.org/3/library/copy.html

In [42]:
list1 = [1, 2, 3, 4]
list2 = list1.copy()
list1[0] = 10
list2[-1] = -10
print('list1', list1)
print('list2', list2)

list1 [10, 2, 3, 4]
list2 [1, 2, 3, -10]


## Compréhension de liste

### Syntaxe

**`list2 = [n*2 for n in list1]`**

> `list2` contient chaque élément de `list1` multiplié par 2.

La compréhension de liste est une expression qui permet de construire une liste à partir de tout autre type itérable (liste, tuple, chaîne de caractères…) en une ligne. Le résultat obtenu est toujours une liste.

### Exercice

- Calculez les carrés des entiers de 1 à 10

In [43]:
[ n**2 for n in range(1,11) ]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

- Maintenant calculez leur somme en utilisant la fonction `sum`

In [44]:
sum( [ n**2 for n in range(1,11) ] )

385

### Condition

Les compréhensions de liste peuvent aussi impliquer une condition **`if`**

In [45]:
[entier for entier in range(20) if entier%2==0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

### Exercice

- La somme des nombres impairs inférieurs à n est égal à $(n/2)^2$. Le vérifier pour $n=20$.

In [46]:
sum([n for n in range(20) if n%2==1])

100

- Décrire en compréhension la liste des nombres inférieurs à 20 qui sont multiples, ou bien de 5, ou bien de 7.

In [47]:
[n for n in range(20) if n%5==0 or n%7==0]

[0, 5, 7, 10, 14, 15]

- Même exercice pour les nombres multiples de 5 ou de 7 mais pas de 15.

In [48]:
[n for n in range(20) if (n%5==0 or n%7==0) and n%15!=0]

[5, 7, 10, 14]

## String

En Python, les strings sont manipulables comme des listes de charactères.

In [49]:
S = 'cordel'
S

'cordel'

On peut notamment accéder aux caractères individuellement :

In [50]:
S[0]

'c'

In [51]:
for lettre in S:
    print(lettre)

c
o
r
d
e
l


### Manipulations de string

**`machaine.split(c)`**
> Sépare `machaine` en utilisant le (ou les) caractères `c` comme séparateur.

**`c.join(maliste)`**
> Rassemble `maliste` en utilisant la chaîne `c` comme séparateur

**`machaine.lower()`**
> Met tous les charactères de `machaine` en minuscule.

**`machaine.replace(a, b)`**
> Remplace les caractères données par `a` par ceux données par `b`

**Exercices**

- Écrire une fonction `nombreOcurrences(x, mot)` qui prend en argument un caractère `x` et une chaîne de caractère `mot` et qui renvoie le nombre de fois où le caractère `x` est présent dans `mot`. Par exemple, si `mot` est `'java'`, `nombreOcurrences(’a’, mot)` vaut 2

In [134]:
def nombreOcurrences(x, mot):
    return sum([c == x for c in mot])

In [53]:
nombreOcurrences('a', 'java')

2

- Écrire une fonction `premierMot(chaine)` qui renvoie le premier mot d’une chaîne de caractère. Par exemple si ma chaîne est `"samedi soir, je vais au cinéma"`, on renverra `"samedi"`.

In [54]:
def premierMot(chaine):
    return chaine.split(' ')[0]

In [55]:
premierMot("samedi soir, je vais au cinéma")

'samedi'

- Remplacer les `\\` par des `/` dans la chaîne suivante

In [140]:
chemin = "C:\\Users\\Quentin\\Documents\\Perso\\Ne pas ouvrir\\francois.jpg"

In [142]:
chemin.replace('\\', '/')

'C:/Users/Quentin/Documents/Perso/Ne pas ouvrir/francois.jpg'

## Les dictionnaires

```
D = {
    clé1 : valeur1,
    clé2 : valeur2,
}
```

Les dictionnaires sont des objets pouvant en contenir d'autres, à l'instar des listes. Cependant, au lieu d'héberger des informations dans un ordre précis, **ils associent chaque objet contenu à une clé** (la plupart du temps, une chaîne de caractères). Par exemple, un dictionnaire peut contenir un carnet d'adresses et on accède à chaque contact en précisant son nom.

- Créer un dictionnaire avec les couples clés-valeurs suivants:  
('Batman','Robin')  
('Harley Quinn','Poison Ivy')  
('Iron man','War machine')  
('Phenix','Cyclope')

In [58]:
dico_duo = {
    'Batman':'Robin',
    'Harley Quinn':'Poison Ivy',
    'Iron man':'War machine',
    'Phenix':'Cyclope'
}
dico_duo

{'Batman': 'Robin',
 'Harley Quinn': 'Poison Ivy',
 'Iron man': 'War machine',
 'Phenix': 'Cyclope'}

**Exercices**

- Acceder au partenaire de `'Phenix'` en utilisant les `[]`

In [59]:
dico_duo['Phenix']

'Cyclope'

- Remplacer la valeur associée à la clé `'Phenix'` par `'Jean Grey'`

In [60]:
dico_duo['Phenix'] = 'Jean Grey'
dico_duo

{'Batman': 'Robin',
 'Harley Quinn': 'Poison Ivy',
 'Iron man': 'War machine',
 'Phenix': 'Jean Grey'}

- Ajouter le duo `'Ant man'` et `'the Wasp'` au dictionnaire

In [61]:
dico_duo['Ant man'] = 'The Wasp'
dico_duo

{'Batman': 'Robin',
 'Harley Quinn': 'Poison Ivy',
 'Iron man': 'War machine',
 'Phenix': 'Jean Grey',
 'Ant man': 'The Wasp'}

# Manipulation de dictionnaires

**`k in dict`**

> Vérifie si la clé `k` est présente dans le dictionnaire

**`for k in dict:`**

> Lorsqu'on itère sur un dictionnaire, on incrémente la clé. Pour obtenir la valeur, il suffit de faire `dict[k]` dans la boucle.

In [62]:
for k in dico_duo:
    print(k, dico_duo[k])

Batman Robin
Harley Quinn Poison Ivy
Iron man War machine
Phenix Jean Grey
Ant man The Wasp


**`dict.items()`**

> La fonction `items()` renvoie les couples (clé, valeur) du dictionnaire. Il est possible d'itérer dessus de la manière suivante : `for k,v in dict.items()`

In [63]:
for k, v in dico_duo.items():
    print(k, v)

Batman Robin
Harley Quinn Poison Ivy
Iron man War machine
Phenix Jean Grey
Ant man The Wasp


**`dict.values()`**

> La fonction `values()` renvoie les valeurs du dictionnaire.

In [64]:
d = {'nom': 'Dupuis', 'prenom': 'Jacques', 'age': 30}

**Exercice**

- Vérifiez si la valeur 30 est dans le dictionnaire `d`

In [65]:
30 in d.values()

True

- Afficher les clés pour lesquelles la valeur est une chaîne de caractères

In [66]:
for k, v in d.items():
    if isinstance(v, str):
        print(k)

nom
prenom


## Dict comprehension

La compréhension de dictionnaire est similaire à la compréhension de liste, à la différence près que les `[]`sont remplacés par des `{}` et que l'expression doit comporter `<clé>:<valeur>`. Cela permet donc de créer un dictionnaire rapidement.

In [67]:
{str(i):i for i in [1,2,3,4,5]}

{'1': 1, '2': 2, '3': 3, '4': 4, '5': 5}

**Exercice**

- A partir de la liste fruits définie ci-dessous, créez un dictionnaire dont les clefs sont les fruits (strings) et les valeurs sont les longueurs de chaînes de caractère de chaque fruit.

In [68]:
fruits = ['apple', 'mango', 'banana','cherry']

In [69]:
{f:len(f) for f in fruits}

{'apple': 5, 'mango': 5, 'banana': 6, 'cherry': 6}

## Les tuples

Les tuples sont des listes immutables, c'est-à-dire que leurs valeurs ne peuvent pas être modifiées. Leur définition se fait avec `()` et leur manipulation est similaire à celle des listes.

In [70]:
ducks = ('riri', 'fifi', 'loulou')

for d in ducks:
    print(d)

riri
fifi
loulou


**Exercice**

- Accédez au deuxième élément du tuple (indice 1)

In [71]:
ducks[1]

'fifi'

# Manipulations de tuples

Maintenant que vous connaissez les manipulations de listes, appliquons les mêmes syntaxes aux tuples. 

- Créer un tuple de 1 à 5 (avec `()`)

In [72]:
t = (1,2,3,4,5)

 - Accéder au chiffre 2 

In [73]:
t[1]

2

- Récupérer les valeurs allant de 1 à 3

In [74]:
t[0:3]

(1, 2, 3)

- Manipulation de tuple

In [75]:
t1 = (1, 2, 3)
t2 = (4, 5, 6)
t3 = (2, 4, 6)

- Concatener les tuples t1 avec t3 et appeler le t4

In [76]:
t4 = t1+t3

- Créer un tuple de tuple t24 contenant t2 et t4

In [77]:
t24 = (t2, t4)

- Afficher la 4e valeur du 2e tuple de t24

In [78]:
t24[1][3]

2


## Les sets

Les ensembles (sets) sont des séquences non ordonnées et non indexables de valeurs distinctes. Elles se définissent grâce aux `{}`. Elles sont très pratiques pour calculer des intersections ou des unions d'éléments distincts uniques. 

In [79]:
fruits1 = {"apple", "banana", "cherry"}
fruits2 = {"orange", "pear","apple"}
print(fruits1)
print(fruits2)

{'apple', 'banana', 'cherry'}
{'orange', 'apple', 'pear'}


In [80]:
fruits1.intersection(fruits2)

{'apple'}

In [81]:
fruits1.union(fruits2)

{'apple', 'banana', 'cherry', 'orange', 'pear'}

Ils peuvent aussi permettre de supprimer les doublons des listes (en perdant l'ordre)

In [82]:
l = ['toto', 'tata', 'titi', 'titi', 'tutu']

list(set(l))

['toto', 'titi', 'tata', 'tutu']

# Aller plus loin avec les itérables

## Des boucles pythonesques

### Enumerate

En suivant la logique de python, on parcourt un itérable avec la synthaxe suivante :

<pre><code>
for <i>élément</i> in itérable:
    ... <i>élément</i> ...
</pre>

Seulement il arrive que l'on ai besoin de l'**indice** de l'élément courant dans la boucle. Pour ca, il existe la fonction **`enumerate`** :

<pre><code>
for <i>indice</i>, <i>élément</i> in <b>enumerate</b>(itérable):
    ... <i>indice</i> ...
    ... <i>élément</i> ...
</pre>

- Affichez chaque élément et chaque indice correspondant de la liste suivante

In [83]:
colors = ["red", "green", "blue", "purple"]

In [84]:
for i, c in enumerate(colors):
    print(i, c)

0 red
1 green
2 blue
3 purple


### Zip

Il arrive parfois que l'on souhaite itérer sur deux listes en même temps. Pour éviter de passer par une boucle sur un indice (comme en matlab par exemple), python intègre la fonction **`zip`** qui permet de "coller" deux listes : 

<pre><code>
for <i>élément_a</i>, <i>élément_b</i> in <b>zip</b>(list_a, list_b):
    ... <i>élément_a</i> ...
    ... <i>élément_b</i> ...
</pre>

In [85]:
number_list = [3, 2, 1]
str_list = ['three', 'two', 'one']

for n, s in zip(number_list, str_list):
    print(n, s)

3 three
2 two
1 one


## Notion de générateur

Exemples d'itérables : 
```
A = [1, 2, 3, 4, 5]
B = range(5)
```

A et B contiennent les mêmes données. Mais la grosse différence, c'est que dans la liste A, tous les éléments sont déjà calculés et stockés en mémoire. Tandis que pour l'objet B, le calcul est effectué à la volée pour chaque itération.

**C'est le principe du générateur** : une fonction qui utilise le mot-clef `yield` au lieu de `return` et qui n'est exécuté que lorsqu'elle est itérée dans une boucle `for`.

In [86]:
def mon_generateur():
    i = 40
    while i <= 56:
        i += 2
        yield i

### Exercice : les itérateurs / générateurs

Créer un générateur infini pour la suite de Fibonacci :
```
Fib[0] = 0
Fib[1] = 1
Fib[n+2] = Fib[n] + Fib[n+1]
```

In [87]:
def fibonacci():
    f1 = 0
    yield f1
    f2 = 1
    yield f2
    while True:
        f3 = f1 + f2
        yield f3
        f1 = f2
        f2 = f3

## Programmation fonctionnelle

### Map

On peut appliquer une fonction sur tous les éléments d'un itérable, à l'aide de la fonction `map`

In [88]:
def double(x):
    return 2*x

l = [1, 2, 3]

l2 = map(double, l)

l2

Le résultat retourné est un générateur. On peut le parcourir :

In [89]:
l2 = map(double, l)

for x in l2:
    print(x)

2
4
6


On peut aussi le convertir directement en liste :

In [90]:
l2 = map(double, l)

list(l2)

[2, 4, 6]

Si la fonction à appliquer n'est pas trop complexe, on peut la définir à la volée à l'aide des `expressions lambda`, qui sont des fonctions anonymes

In [91]:
list(map(lambda x: 2*x, [1, 2, 3]))

[2, 4, 6]

Pour des fonctions simples une compréhension de liste est néanmoins plus lisible :

In [92]:
[2*x for x in [1, 2, 3]]

[2, 4, 6]

### Filter

`filter` permet de garder les éléments en fonction d'un critère booléen

In [93]:
def is_impair(x):
    return x%2 == 1

list(filter(is_impair, range(10)))

[1, 3, 5, 7, 9]

**Exercice**

Réécrire la compréhension de liste avec map et filter :
`[i**2 for i in range(10) if i%2 ==1]`

In [94]:
list(map(lambda x: x**2, filter(lambda x: x%2==1, range(10))))

[1, 9, 25, 49, 81]

# Packages

Python dispose de nombreux packages pour faire des tâches plus spécialisées.

Par exemple `numpy` est un package spécialisé dans le calcul numérique, permettant de manipuler des tableaux et de faire du calcul matriciel.

In [95]:
# Installation de numpy
!pip install numpy

Il existe différentes façons de charger un package :
- `import numpy` permet de charger tout le package. Ainsi la fonction `array` de `numpy` pourra être appellée sous la forme `numpy.array`
- `import numpy as np` permet de faire la même chose mais en changeant le nom à utiliser : `np.array`. C'est une façon très courante de faire pour certains packages dont l'abréviation est courante (`np` pour `numpy`, `pd` pour `pandas`, etc.). Évitez d'inventer vos propres abrévations !
- `from numpy import array` permet de ne charger que la fonction `array` et de l'appeler directement. Dans la mesure où cela fait perdre de vue l'origine de la fonction et où cela peut créer des conflits entre fonctions ayant le même nom mais venant de différents packages, c'est à utiliser avec parcimonie !

# Numpy

In [96]:
import numpy as np

Numpy est la librairie de calcul numérique de python. Elle permet d'effectuer efficacement des opérations sur des vecteurs ou des matrices, appelées **"arrays"**. Ces tableaux se manipulent de la même manière que les listes de base : **`A[0:3]`** renvoie les 4 premières valeurs du vecteur `A`. Mais nous verrons leur intérêt pour le calcul matriciel.

Mais ces tableaux sont adaptés au calcul matriciel :

## Des tableaux de toutes les tailles

On peut créer un vecteur (array 1D) à partir de la liste des valeurs

In [148]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

Ils peuvent être 2D. On les construit avec des listes de listes

In [152]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

On peut récupérer les dimensions du tableau grâce à `shape`

In [194]:
b.shape

(2, 3)

On peut aussi faire des tableaux 3D voire plus

In [197]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [198]:
c.shape

(2, 2, 2)

La fonction `reshape` permet de changer la forme de l'array, tant qu'on garde le même nombre d'éléments. Elle prend comme argument le tuple des dimensions souhaités (ou un entier pour un tableau 1D).

In [187]:
np.reshape(b, (6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [189]:
np.reshape(b, 6)

array([1, 2, 3, 4, 5, 6])

On peut aussi utiliser la valeur `-1` pour laisser numpy déterminer la taille adéquate

In [190]:
np.reshape(b, (3, -1))

array([[1, 2, 3, 4, 5, 6]])

In [191]:
np.reshape(b, -1)

array([1, 2, 3, 4, 5, 6])

## Tableaux classiques

Certains tableaux classiques peuvent être construits directement, en fournissant le tuple des dimensions souhaités

In [155]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [159]:
np.ones(4)

array([1., 1., 1., 1.])

In [205]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [160]:
np.random.random((3, 3))

array([[0.54420816, 0.08209492, 0.3663424 ],
       [0.8508505 , 0.40627504, 0.02720237],
       [0.24717724, 0.06714437, 0.99385201]])

In [201]:
np.random.randint(1, 6, 10)

array([2, 4, 4, 1, 2, 5, 3, 2, 2, 3])

## Indexation

L'indexation peut se faire comme pour les listes sous la forme d'un entier ou d'un intervalle (début:fin:pas)

In [209]:
a

array([1, 2, 3])

In [207]:
a[0]

1

In [208]:
a[-2:]

array([2, 3])

Cette syntaxe s'étend pour les tableaux multidimensionnels

In [210]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [168]:
b[0, 1]

2

In [169]:
b[0, 1:]

array([2, 3])

In [170]:
b[:, 1:]

array([[2, 3],
       [5, 6]])

On peut aussi utiliser l'indexation booléenne, en lui passant un tableau de True/False

In [211]:
is_impair = a%2==1

a[is_impair]

array([1, 3])

## Calcul matriciel

Le principal apport des tableaux numpy par rapport aux listes Python et leur facilité d'utilisation pour le calcul matriciel. Les principales opérations peuvent se faire par élément

In [213]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y

array([5, 7, 9])

In [214]:
b*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

La multiplication de tableaux 2D se fait élément par élément. La multiplication matricielle peut se faire par la fonction `dot`

In [178]:
b*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [185]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [186]:
np.dot(b, b.T)

array([[14, 32],
       [32, 77]])

`numpy` propose aussi différentes fonctions mathématiques

In [162]:
np.median(a)

2.0

In [215]:
np.std(a) # écart-type

0.816496580927726

In [216]:
np.sum(b)

21

In [183]:
np.sum(b, axis=0) # somme sur les colonnes

array([5, 7, 9])

In [184]:
np.sum(b, axis=1) # somme sur les lignes

array([ 6, 15])

# Gestion des erreurs

En Python, il est facile de gérer des erreurs grâce à `try`.

La manière simple de l'utiliser est :

In [144]:
dico = {'a': 1, 'b': 2}

try:
    print(dico['c'])
except:
    print("Clé absente mais c'est pas grave")

Clé absente mais c'est pas grave


Si on ne veut rien faire en cas d'erreur et continuer comme si de rien n'était, on peut utiliser `pass`

In [146]:
try:
    code_qui_plante
    print('Oups')
except: 
    pass